### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-facebook#1]
@hdrdavies do you have a module in mind to use or are you going to do this without any dependencies like the https://github.com/dwyl/hapi-auth-github plugin?

**Comment by hdrdavies** [comment]
@nelsonic no module in mind as of yet but we (@jackcarlisle @des-des) will research this :+1:

**Comment by nelsonic** [comment]
Sweet. document-all-the-things! :+1:

**Comment by nelsonic** [comment]
No longer relevant as dependencies removed. Closing. ✅ 
Thanks again gents! Hope you're all well. ❤️
