### ISSUE TITLE
Use `module.exports` to provide function to create initial auth url

### ISSUE THREAD

**Issue by des-des** [dwyl/elixir-auth-facebook#12]
So that instead of using this handler to create the first auth url: https://github.com/dwyl/hapi-auth-facebook/blob/master/lib/index.js#L67 we do something more like this: https://github.com/dwyl/hapi-auth-github/blob/master/lib/index.js#L97.

**Comment by nelsonic** [comment]
Closing as no longer relevant. ✅ 
Miss you Eoin! Hope you're well. ❤️
